# -*- coding: utf-8 -*-
"""2024-09-04-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13R8EjU9VxE1Eqq_9jzAPkbWOdhh0iKtL
"""

print("Hello World")

print("참깨빵위에 순쇠고기 패티 두 장 특별한 소스 양상추 치즈 피클 양파까지")



"""##

###

# 새 섹션
"""

import pylab as py

x_deg = py.arange(-180,180+1)
x_rad = py.deg2rad(x_deg)
y = py.sin(x_rad)

py.plot(x_deg,y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)

